apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-service
  template:
    metadata:
      labels:
        app: sample-service
    spec:
      containers:
      - name: sample-service
        image: cr.yandex/crpe7gmtkh8el8rkf2ub/sample_service:latest
        ports:
        - containerPort: 80  # Укажите порт, который использует ваш сервис